# Generated by Django 3.2.15 on 2022-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_pachislotstore_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pachislotstore',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メモ'),
        ),
    ]
