# Generated by Django 3.2.15 on 2022-09-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pachislotstore_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessday',
            options={'verbose_name_plural': '営業日'},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name_plural': '機種名'},
        ),
    ]
