# Generated by Django 3.2.15 on 2022-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220906_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessday',
            name='total_pay',
            field=models.IntegerField(default=777, verbose_name='総差枚数'),
            preserve_default=False,
        ),
    ]
