# Generated by Django 3.2.15 on 2022-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_businessday_total_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='total_pay',
            field=models.IntegerField(null=True, verbose_name='総差枚数'),
        ),
    ]
