# Generated by Django 3.2.15 on 2022-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_businessday_total_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='lastgames',
            field=models.IntegerField(null=True, verbose_name='宵越し'),
        ),
    ]
