# Generated by Django 3.2.15 on 2022-09-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220909_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name_plural': '台データ'},
        ),
        migrations.CreateModel(
            name='SlotTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='機種名')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='メモ')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.businessday')),
            ],
            options={
                'verbose_name_plural': '機種名',
            },
        ),
    ]
