# Generated by Django 3.2.15 on 2022-09-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220917_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottitle',
            name='numbers',
            field=models.IntegerField(null=True, verbose_name='台数'),
        ),
        migrations.AlterField(
            model_name='slottitle',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='slot_title', to='app.businessday'),
        ),
    ]
