# Generated by Django 3.2.15 on 2022-09-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220917_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pachinko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='機種名')),
                ('number', models.IntegerField(verbose_name='台番号')),
                ('bonus', models.IntegerField(verbose_name='当たり')),
                ('count', models.IntegerField(verbose_name='総回転数')),
                ('lastgames', models.IntegerField(null=True, verbose_name='宵越し')),
                ('payout', models.IntegerField(verbose_name='差枚数')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='メモ')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.businessday')),
            ],
            options={
                'verbose_name_plural': 'パチンコ',
            },
        ),
    ]
