# Generated by Django 3.2.15 on 2022-09-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_pachinko'),
    ]

    operations = [
        migrations.AddField(
            model_name='pachinko',
            name='game_1k',
            field=models.FloatField(null=True, verbose_name='1kあたり目安'),
        ),
    ]
