# Generated by Django 3.2.15 on 2022-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pachinko_bbchance'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessday',
            name='total_pay_pachinko',
            field=models.IntegerField(null=True, verbose_name='総出玉数'),
        ),
    ]
